server:
  # 服务端口号
  port: 8762
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: user-service
  data:
    mongodb:
      host:
        localhost
      port:
        27017
      username:
        root
      password:
        example
      database:
        user_server
  redis:
    database:
      0
    host:
      localhost
    port:
      6379
    jedis:
      pool:
        max-active:
          50
        max-wait:
          -1
        max-idle:
          10
        min-idle:
          0
    connect-timeout:
      1000
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://localhost:3306/COC?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    data-username:
      root
    password:
      1Chenghan
  rabbitmq:
    host:
      localhost
    port:
      5672
    virtual-host:
      /user
    username:
      root
    password:
      1Chenghan

eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://localhost:8761/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
