server:
  # 服务端口号
  port: 8762
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName:
        com.mysql.cj.jdbc.Driver
      url:
        jdbc:mysql://localhost:3306/coc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      username:
        root
      password:
        1Chenghan
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: user-service
  redis:
    database:
      0
    host:
      localhost
    port:
      6379
    jedis:
      pool:
        max-active:
          50
        max-wait:
          -1
        max-idle:
          10
        min-idle:
          0
    connect-timeout:
      1000

mybatis-plus:
  configuration:
    use-column-label: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package:
    com.tisu.user.entity
logging:
  level:
    com:
      tisu:
        user:
          mapper:
            debug

eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://localhost:8761/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
