server:
  # 服务端口号
  port: 8763
spring:
  data:
    mongodb:
      database:
        warehouse
      host: localhost
      port: 27018
      username: root
      password: 1Chenghan
  application:
  # 服务名称 - 服务之间使用名称进行通讯
    name: warehouse-service
  redis:
    database:
      0
    host:
      localhost
    port:
      6379
    jedis:
      pool:
        max-active:
          50
        max-wait:
          -1
        max-idle:
          10
        min-idle:
          0
    connect-timeout:
      1000
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 1Chenghan
