server:
  # 服务端口号
  port: 8763
spring:
  devtools:
    livereload:
      port: 35731
  data:
    mongodb:
      uri: mongodb://root:1Chenghan@localhost:27018/warehouse?authSource=admin&authMechanism=SCRAM-SHA-1
  application:
  # 服务名称 - 服务之间使用名称进行通讯
    name: warehouse-service
  redis:
    database:
      0
    host:
      localhost
    port:
      6379
    jedis:
      pool:
        max-active:
          50
        max-wait:
          -1
        max-idle:
          10
        min-idle:
          0
    connect-timeout:
      1000
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 1Chenghan
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://localhost:8761/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/html, application/xml, application/json
      min-request-size: 2048
    response:
      enabled: true
